---
abstract: 'Perl extention to output time list'
author:
  - '<<Shinichiro Sato>> <<<s2otsa59@gmail.com>>>'
build_requires:
  Class::Accessor::Lite: 0
  Data::Util: 0
  Test::More: 0.98
  Time::Piece: 1.24
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.8.0, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Time-List
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Time::List:
    file: lib/Time/List.pm
    version: 0.07
  Time::List::Constant:
    file: lib/Time/List/Constant.pm
  Time::List::Rows:
    file: lib/Time/List/Rows.pm
    version: 0.07
  Time::List::Rows::Row:
    file: lib/Time/List/Rows/Row.pm
    version: 0.07
requires:
  perl: 5.008001
resources:
  bugtracker: https://github.com/S2/p5-Time-List/issues
  homepage: https://github.com/S2/p5-Time-List
  repository: https://github.com/S2/p5-Time-List.git
version: 0.07
x_contributors:
  - 'sato sin <shinichiro@wano.co.jp>'
